version: '3'
services:
  backend:
    image: docker.io/methusshan25/les-backend:latest
    ports:
      - "8080:8080"
  frontend:
    image: docker.io/methusshan25/les-frontend:latest
    ports:
      - "5173:5173"